# Generated by Django 5.2.8 on 2025-11-07 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treasurer',
            name='is_approved',
        ),
    ]
