# Generated by Django 5.2.8 on 2025-11-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_fund_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='fund_type',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
