# Generated by Django 5.2.8 on 2025-11-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_fund_fund_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='default_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Default percentage of offerings to be allocated to this fund.', max_digits=5),
        ),
    ]
