# Generated by Django 5.2.8 on 2025-11-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_fund_default_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('OFFERING', 'Offering'), ('WITHDRAWAL', 'Withdrawal')], max_length=20),
        ),
    ]
