# Generated by Django 5.2.8 on 2025-11-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasurer',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Designates whether the user is an approved treasurer.'),
        ),
    ]
