# Generated by Django 5.2.8 on 2025-11-19 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_treasurer_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_allocated', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.fund')),
                ('parent_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='myapp.transaction')),
            ],
        ),
    ]
