# Generated by Django 5.2.8 on 2025-11-19 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_transactionsplit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.fund'),
        ),
    ]
